baseURL = "https://bitfuseio.github.io/bitfuse.io/"
languageCode = "en-US"
title = "bitfuse.io"
theme = "icon"
publishDir = "docs"

[params]

[params.hero]
img = "backdrop.png"
title = "bitfuse.io"
description = "lean and cloud-native software engineering"

[params.nav]
mission = "Our Mission"
services = "Services"
team = "The Team"
contact = "Get In Touch"

[params.mission]
enable = true

[[params.mission.item]]
weight = 1
description = "<p>At bitfuse.io we love software. Especially if it's simple and efficient. Software should be built to fulfill its requirements and nothing more.</p><p>We focus on providing services that are to the point and solve your problems as efficiently as possible. Good solutions are</p><ul class='checked'><li>easy to operate</li><li>adaptable to change</li><li>scalable under load</li><li>essential to your business</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

[params.services]
enable = true
title = "Our Services"
description = "bitfuse.io is the right match for every phase of your project:"

[[params.services.item]]
icon = "icon-pencil"
title = "Design"
description = "A diagram says more than a thousand words. Let's structure your business domain."

[[params.services.item]]
icon = "icon-present"
title = "Build"
description = "From napkin to code. We help you realize your ideas as lean and cloud-native software."

[[params.services.item]]
icon = "icon-eye"
title = "Run"
description = "Zero downtime. Together we continuously deploy your applications at scale."

[[params.services.item]]
icon = "icon-paper-plane"
title = "Rethink"
description = "Everything is simple in hindsight. Let's embrace that fact and take your software to the next level."

[params.work]
enable = false

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_1.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_2.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_3.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_2.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_3.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_2.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_3.jpg"

[[params.work.item]]
title = "Consectetur adipisicing"
subtitle = "Web Design"
img = "images/img_4.jpg"

[params.team]
enable = true
title = "Meet The Team"

[[params.team.item]]
name = "Mathis Kretz"
position = "Keeper of Simple"
description = "Software Architect specialized in microservices, container technologies and cloud-native engineering"
img = "https://pbs.twimg.com/profile_images/650392554882662400/rAxkf18s_400x400.jpg"
twitter = "https://twitter.com/mathis_kretz"
github = "https://github.com/mkretz"

[[params.team.item]]
name = "Tobi Fuhrimann"
position = "Head in the Clouds"
description = "Software Engineer specialized in cloud services, distributed systems and web development with modern technologies"
img = "https://pbs.twimg.com/profile_images/928975001105166336/dhnwx8fA_400x400.jpg"
twitter = "https://twitter.com/mastertinner"
github = "https://github.com/mastertinner"

[params.contact]
enable = true
title = "Get In Touch"
message = "We'd love to work with you! Let us know how we can support you."
name_placeholder = "Your name"
email_placeholder = "Your email"
email_disclaimer = "We'll never share your email with anyone else."
message_placeholder = "Please enter a message."
button_text = "Submit"

[params.footer]
enable = true
github = "https://github.com/orgs/bitfuseio"
twitter = "#"
