name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    environment: aws-production
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Audit dependencies
      #   run: npm audit
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Deploy to production
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
