name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    environment: aws-production
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/setup-node@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      # - run: npm audit
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
